package tetris;

import java.awt.*;

/**
 * Application Class. Window initialisation
 *
 * @author Lei Gao
 */
public class TetrixApp extends javax.swing.JFrame {

    private static final long serialVersionUID = -7369891504478654529L;

    protected static GamePanel gamePanel = new GamePanel();

    protected static TestPanel testPanel = new TestPanel();

    protected static ScorePanel scorePanel = new ScorePanel();

    private InfoPanel infoPanel = new InfoPanel();

    private Panel leftPanel = new Panel();

    public TetrixApp() {
        initComponents();
        setSize(540, 575);
        leftPanel.setLayout(new BorderLayout(10, 10));

        leftPanel.add(scorePanel, BorderLayout.NORTH);
        leftPanel.add(testPanel, BorderLayout.CENTER);
        leftPanel.add(infoPanel, BorderLayout.SOUTH);
        this.getContentPane().add(leftPanel);
        this.getContentPane().add(gamePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        getContentPane().setLayout(new FlowLayout());
        this.setLocationByPlatform(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris Demo - Author: Alan Gao (cgaolei @ github)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        pack();
    }

    /**
     * Main program entry
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TetrixApp().setVisible(true);
                gamePanel.t.start();
            }
        });
    }
}
